services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: signup-app:dev
    container_name: signup_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    container_name: signup_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: postgres:16
    container_name: signup_db
    environment:
      POSTGRES_DB: signupform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: signup_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5050:80"

volumes:
  pgdata:
