version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: signup-app:dev
    container_name: signup_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      - vendor_cache:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=signupform
      - DB_USERNAME=postgres
      - DB_PASSWORD=123
    depends_on:
      - db
    entrypoint: /usr/local/bin/entrypoint.sh

  nginx:
    image: nginx:1.25
    container_name: signup_nginx
    restart: unless-stopped
    ports:
      - "8080:80" # acesse http://localhost:8080
    volumes:
      - ./:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: postgres:16
    container_name: signup_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: signupform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: signup_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5050:80"

volumes:
  pgdata:
  vendor_cache:
  node_modules:
